### ISSUE TITLE
Something is terrible wrong

### ISSUE THREAD

**Issue by FDiskas** [MaximilianPichler/material-ui-selectfield#14]
I tried this against `material-ui-superselectfield` and your version is working much faster.
![vytenis kuciauskas-20171017111236-644x253](https://user-images.githubusercontent.com/468006/31653682-1d0d5fe4-b32c-11e7-915c-fe31ab66a7f0.png)

Please do not close this fork.

**Comment by TarikHuber** [comment]
We are working together with @Sharlan to implement this code into the superselect field project. It will take some time but we will have just one project with the best from both 😁

**Comment by MaximilianPichler** [comment]
Hi!
The fork is currently online until I have more time to clear things up and port everything to material-ui-superselectfield.

**Comment by FDiskas** [comment]
For me it's a bad news :)
Can't use this fork, and can't use superselectfield because of lack features and performance issues. :hospital:

**Comment by MaximilianPichler** [comment]
Just use this fork. I will let you know when we have fully transitioned. And don't worry: The NPM package will stay up, so older projects still work.
