### ISSUE TITLE
Search by label and value

### ISSUE THREAD

**Issue by FDiskas** [MaximilianPichler/material-ui-selectfield#2]
Currently the search is done only on value, but not by Label
![ezgif com-optimize 1](https://user-images.githubusercontent.com/468006/31214233-f9504364-a9b2-11e7-9613-cbdf2054d631.gif)

**Comment by MaximilianPichler** [comment]
Hey!
Thanks for opening the issue! I fixed it. Now the autocomplete searches the label if available. If there is no label it searches by value.
Try out version 1.0.14 and let me know if it works for you.

**Comment by FDiskas** [comment]
And there is another issue. As you can see in a gif - selected item is displayed by value, not by label. For the user is not informative to see the ID's of items :/
And updated version the search is not working by label.
```js
getElemets2(count) {
        const elements = [];
        for (let i = 1; i <= count; i++) {
            elements.push(
                <div key={i} value={i}>Option {i}</div>
            );
        }

        return elements;
    }

render() {
        return (
            <SelectField
                name={'demo'}
                multiple={true}
            >
                {this.getElemets2(50)}
            </SelectField>
        );
    }
```

**Comment by FDiskas** [comment]
And in my case "checkbox" icons are gone :/

**Comment by FDiskas** [comment]
Sorry by accidentally closing the issue

**Comment by FDiskas** [comment]
I looked at your demo - looks like attribute "checkPosition='left'" is required if checkboxes needed to be displayed :snowflake:

**Comment by MaximilianPichler** [comment]
Ok I think I have figured it out
You have to set a value and a label property for your divs.
example:
`<div key={i} value={i} label={'Option ${i}'}>Option {i}</div>`
To try it out please use the version 1.0.15

**Comment by MaximilianPichler** [comment]
Yeah if no checkPosition is set, the checkboxes are not shown. I will update the readme to make it more clear.

**Comment by FDiskas** [comment]
`<div key={i} value={i} label={'Option ${i}'}>Option {i}</div>` did't worked. I'm reprodusing this on your repository by adding one more demo to it with suggested syntax :white_small_square:

**Comment by MaximilianPichler** [comment]
Are you sure you are using the version 1.0.15?

**Comment by FDiskas** [comment]
Thanks - you are releasing to fast :)
works now :trollface:
