### ISSUE TITLE
Using yarn

### ISSUE THREAD

**Issue by FDiskas** [MaximilianPichler/material-ui-selectfield#3]
```
ERROR in ./node_modules/material-ui-selectfield/es/SelectField.js
Module not found: Error: Can't resolve 'react-infinite' in '/***/node_modules/material-ui-selectfield/es'
```

**Comment by TarikHuber** [comment]
Try to install react-infinite manually. I think it is a dependency put not set to the peer dependencies.

**Comment by FDiskas** [comment]
Probably should be in readme. :watermelon:

**Comment by MaximilianPichler** [comment]
react-infinite is set as a peer-dependency. I will update the readme to list the dependencies
